on:
  push:
    branches:
      - rt-dev
      - rt-demo

name: Astra Theme Deployment
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: rtCamp/action-deploy-wordpress@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        WP_VERSION: 5.6
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: bots-google
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Cleanup
      if: ${{ always() }}
      uses: rtCamp/action-cleanup@master
